/* SHARED CONSTANTS */
export const CLEAR_STORE = 'CLEAR_STORE';
export const TOGGLE_CLICK = 'TOGGLE_CLICK';

/* COMMENTS CONSTANTS */
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENT';
export const ADD_NEW_COMMENT = 'ADD_NEW_COMMENT';

/* BOARD CONSTANTS */
export const RECEIVE_BOARD = 'RECEIVE_BOARD';
export const RECEIVE_BOARDS = 'RECEIVE_BOARDS';
export const ADD_NEW_BOARD = 'ADD_NEW_BOARD';
export const RECEIVE_BOARD_NOTES = 'RECEIVE_BOARD_NOTES';
export const RECEIVE_PERMISSION = 'RECEIVE_PERMISSION';


/* NOTE CONSTANTS */
export const SELECT_NOTE = 'SELECT_NOTE';
export const RECEIVE_NOTE = 'RECEIVE_NOTE';
export const RECEIVE_NOTES = 'RECEIVE_NOTES';
export const ADD_NOTE_TO_BOARD = 'ADD_NOTE_TO_BOARD';
export const SET_NOTE_COORDS = 'SET_NOTE_COORDS';
export const NOTE_ARRAY_INDEX_PUSH = 'NOTE_ARRAY_INDEX_PUSH';
export const DELETE_NOTE = 'DELETE_NOTE';
export const NOTE_DETAIL = 'NOTE_DETAIL';
export const CHANGE_NOTE_SIZE = 'CHANGE_NOTE_SIZE';
export const SET_UNREAD_NOTE_NUMBER = 'SET_UNREAD_NOTE_NUMBER';
export const SET_MENTIONED_NOTES = 'SET_MENTIONED_NOTES';


/* USER CONSTANTS */
export const SET_LOGIN_USER = 'SET_LOGIN_USER';
export const REMOVE_LOGIN_USER = 'REMOVE_LOGIN_USER';
export const RECEIVE_USER_QUERY = 'RECEIVE_USER_QUERY';

/* NOTEBOARD CONSTANTS */
export const MOVE_NOTE = 'MOVE_NOTE';
export const RECEIVE_MYBOARDS_NOTES = 'RECEIVE_MYBOARDS_NOTES';
export const SET_NOTES_SIZE = 'SET_NOTES_SIZE';

/* ITEM TYPES FOR REACT DND*/
export const NOTE = 'note';

/* SOCKETS */
export const EMIT = 'EMIT';
export const CONNECT = 'CONNECT';
export const ADD_LISTENER = 'ADD_LISTENER';
export const REMOVE_LISTENER = 'REMOVE_LISTENER';
